title: Jan C. Brammer

markdown: kramdown
banner: "./banner.png"

favicon: yes
favicon_location: "./favicon.png"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "resume/resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "GitHub"
   link: "https://github.com/JanCBrammer"
