title: Jan C. Brammer

markdown: kramdown
banner: "./assets/icon.png"
favicon: "./assets/icon.png"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "assets/resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "GitHub"
   link: "https://github.com/JanCBrammer"

latest_update: "April 2024"
